application: html5playbook
version: 2
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img
- url: /samples
  static_dir: samples
- url: /
  script: main.py
- url: /static
  static_dir: static