application: html5playground
version: 2
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  expiration: "10d"
- url: /offline_test/index.html
  static_files: offline_test/index.html
  upload: offline_test/index.html
- url: /offline_test/html5offline.manifest
  static_files: offline_test/html5offline.manifest
  upload: offline_test/html5offline.manifest
  mime_type: text/cache-manifest
- url: /samples/html5_misc/offline.manifest
  static_files: samples/html5_misc/offline.manifest
  upload: samples/html5_misc/offline.manifest
  mime_type: text/cache-manifest
- url: /popout.html
  static_files: popout.html
  upload: popout.html
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "10d"
- url: /images
  static_dir: images
  expiration: "10d"
- url: /css
  static_dir: css
  expiration: "10d"
- url: /codemirror
  static_dir: codemirror
  expiration: "10d"
- url: /samples/boilerplateHTML/(.*\.html)
  script: boilerplateProxy.py
- url: /index.html
  script: main.py
- url: /samples/js
  static_dir: samples/js
  expiration: "10s"
- url: /samples/css
  static_dir: samples/css
  expiration: "10s"
- url: /samples/html5_misc
  static_dir: samples/html5_misc
  expiration: "10d"
- url: /save
  script: main.py
- url: /delete
  script: main.py
- url: /get
  script: main.py
- url: /cacheCode
  script: main.py
- url: /
  script: main.py
- url: /apis/ajax/playground/js
  static_dir: js
  expiration: "10d"
- url: /apis/ajax/playground/popout.html
  static_files: popout.html
  upload: popout.html
- url: /apis/ajax/playground/favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "10d"
- url: /apis/ajax/playground/images
  static_dir: images
  expiration: "10d"
- url: /apis/ajax/playground/css
  static_dir: css
  expiration: "10d"
- url: /apis/ajax/playground/codemirror
  static_dir: codemirror
  expiration: "10d"
- url: /apis/ajax/playground/samples/boilerplateHTML/(.*\.html)
  script: boilerplateProxy.py
- url: /apis/ajax/playground/index.html
  script: main.py
- url: /apis/ajax/playground/samples/js
  static_dir: samples/js
  expiration: "10s"
- url: /apis/ajax/playground/save
  script: main.py
- url: /apis/ajax/playground/delete
  script: main.py
- url: /apis/ajax/playground/get
  script: main.py
- url: /apis/ajax/playground/cacheCode
  script: main.py
- url: /apis/ajax/playground/
  script: main.py
- url: /apis/ajax/playground
  script: main.py
- url: /apis/ajax/playground/getTOC
  script: main.py
- url: /apis/ajax/playground/flush_memcache
  script: main.py
- url: /apis/ajax/playground/get_projects
  script: main.py
- url: /apis/ajax/playground/ga_error
  script: main.py
